Fix CI issues (#178)
- Fix Travis CI config to fail when any example does not type-check
- Add "no-self-use" to list of ignored Pylint errors due to having too
  many false positives
- Fix incorrect type annotations in sentence_classifier and vae_text
  examples

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -24,17 +24,33 @@ install:
   - pip install --upgrade pip
   - pip install --progress-bar off torch==$TORCH_VER
   - pip install --progress-bar off .[extras]
-  - pip install pylint==2.3.1 flake8==3.7.7
-  - pip install mypy==0.720
+  - if [[ $TORCH_VER == "1.2.0" ]]; then
+      pip install pylint==2.3.1 flake8==3.7.7;
+    fi
+  - if [[ $TORCH_VER != "1.0.1" ]]; then
+      pip install mypy==0.720;
+    fi
   - pip install pytest
 
 script:
-  # linting
-  - pylint texar/ examples/
-  - flake8 texar/ examples/
-  # type-checking (only for PyTorch version 1.2.0)
-  - "if [[ $TORCH_VER != '1.0.1' ]]; then mypy .; fi"
-  - "if [[ $TORCH_VER != '1.0.1' ]]; then for dir in `echo examples/**/`; do mypy $dir; done; fi"
+  # linting (only for PyTorch version 1.2.0 to save time)
+  - if [[ $TORCH_VER == "1.2.0" ]]; then
+      pylint texar/ examples/;
+    fi
+  - if [[ $TORCH_VER == "1.2.0" ]]; then
+      flake8 texar/ examples/;
+    fi
+  # type-checking (only for PyTorch version 1.1.0 & 1.2.0)
+  - if [[ $TORCH_VER != "1.0.1" ]]; then
+      mypy .;
+    fi
+  # type-check all examples; fail if any example does not type-check
+  - if [[ $TORCH_VER != "1.0.1" ]]; then
+      _rc=0;
+      for dir in `echo examples/**/`; do
+        mypy $dir || _rc=$?;
+      done || $_rc;
+    fi
   # unit tests
   - pytest
 
